### ISSUE TITLE
JEI Compat

### ISSUE THREAD

**Issue by Divineaspect** [BrassGoggledCoders/Workshop#11]
It's hard to check anything else without referencing the documentation without that.

**Comment by FreneticScribbler** [comment]
This should exist, is it not working??

**Comment by Divineaspect** [comment]
No for Drying Basin (and hence Seasoned Log), Mortar and Pestle, Collector (and thus Tallow), and Scrap Bin (and accordingly Scrap Bag).

Has JEI when looking at the target item, but no way to look at the machine and see it's uses: Alembic, Press, Seasoning Barrel, Molten Reaction Chamber, Sintering Furnace, and Spinning Wheel.

**Comment by FreneticScribbler** [comment]
* Mortar & Pestle support is in and working... has been for ages
* Drying basin support is in progress
- Collector is pushed back
- I've added an info screen when you hit U on a scrap bag, pending addition of loot table display (this is a bit of a faff)
- Recipe click areas in machine GUIs are also somewhat non trivial because of Titanium but I'll work on them...
